services:
  manage-torrents:
    image: strenkml/qbittorrent-manage-torrents
    build:
      context: .
    restart: unless-stopped
    container_name: qbittorrent-managetorrents
    environment:
      - QBITTORRENT_HOST=127.0.0.1
      - QBITTORRENT_PORT=8080
      - QBITTORRENT_USERNAME=admin
      - QBITTORRENT_PASSWORD=adminadmin
      - QBITTORRENT_UPDATE_TIME_SECONDS=120
